version: '2'
services:
  gk.akm.03:
    mem_limit: 256m
    network_mode: "host"
    build:
      context: .
      target: GK.AKM.03
  gk.go.01:
    mem_limit: 256m
    network_mode: "host"
    build:
      context: .
      target: GK.GO.01
  gk.ktr.01:
    mem_limit: 256m
    network_mode: "host"
    build:
      context: .
      target: GK.KTR.01
  gk.mrb.01:
    mem_limit: 256m
    network_mode: "host"
    build:
      context: .
      target: GK.MRB.01
  gk.rv.01:
    mem_limit: 256m
    network_mode: "host"
    build:
      context: .
      target: GK.RV.01
  gk.rv.02:
    mem_limit: 256m
    network_mode: "host"
    build:
      context: .
      target: GK.RV.02
  gk.ww.01:
    mem_limit: 256m
    network_mode: "host"
    build:
      context: .
      target: GK.WW.01
  gk.zlw.10:
    mem_limit: 256m
    network_mode: "host"
    build:
      context: .
      target: GK.ZLW.10
  gk.zlw.11:
    mem_limit: 256m
    network_mode: "host"
    build:
      context: .
      target: GK.ZLW.11